### ISSUE TITLE
Add sources for Form F4T 

### ISSUE THREAD

**Issue by chadday** [dwillis/fech-sources#6]
Hey Derek, 

As always, thanks for maintaining the wonderful Fech! Would it be possible to add a source file for F4T filings? I've run into this error a few times when we're backfilling for certain dates over the past year. 
```
Attempted to access mapping that has not been generated (F4T).
```
Thanks!

**Comment by dwillis** [comment]
@chadday Should be able to get to that soon.

**Comment by chadday** [comment]
Thanks so much. You're awesome man!

**Comment by dwillis** [comment]
@chadday This was actually an issue with Fech and not the sources. We've [fixed it](https://github.com/dwillis/Fech/commit/c1a5a45b2390db7fc3c71012b326c1d3d7d8433b) on the Fech repository.

**Comment by chadday** [comment]
Awesome. Thanks much!
